baseURL = 'https://loopback.in'
languageCode = 'en-us'
title = "Clement's Blog"
theme = 'ananke'
#pygmentsUseClasses = true
#PygmentsStyle = "monokai"
#pygmentsCodeFences = true
enableRobotsTXT = true
disqusShortname = 'clement89'
googleAnalytics = 'G-1WNJ6RVDVS'
show_reading_time = true
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noHl = false
    style = 'gruvbox'
    tabWidth = 4
