baseURL = 'https://loopback.in'
languageCode = 'en-us'
title = "Clement's Blog"
theme = 'ananke'
pygmentsUseClasses = true
pygmentsCodeFences = true
enableRobotsTXT = true
disqusShortname = 'clement89'
googleAnalytics = 'G-1WNJ6RVDVS'
